#! /bin/sh

#------------------------------------------------
# Start other useful Programs
#------------------------------------------------
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
#nitrogen --restore &
feh --bg-fill ~/.wallpapers/wallpaper-19.jpg
~/./.config/polybar/launch.sh &

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9 10
done

#------------------------------------------------
# My Bpswm Config
#------------------------------------------------
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   30 # Leave space for Polybar
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#------------------------------------------------
# My Bspwm Theme based on Tokyonight colorscheme
#------------------------------------------------
bspc config normal_border_color   "#565f89"
bspc config focused_border_color  "#7aa2f7"
bspc config active_border_color	  "#7aa2f7"
bspc config presel_feedback_color "#7aa2f7"
bspc config urgent_border_color   "#f7768e"

#------------------------------------------------
# Default Bspwm window Rules
#------------------------------------------------
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
